"""add group_id to settlement

Revision ID: 66af33312e56
Revises: 787a7b970308
Create Date: 2026-03-05 22:01:47.006067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66af33312e56'
down_revision = '787a7b970308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
