"""add user_tag

Revision ID: 8a6fa5e6a80d
Revises: b45377e2c923
Create Date: 2026-03-10 18:21:37.647820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6fa5e6a80d'
down_revision = 'b45377e2c923'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('user_tag', sa.String(length=10), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_tag')

    # ### end Alembic commands ###
