"""add total_expense

Revision ID: ac2c778bb0b6
Revises: de323b0f5696
Create Date: 2026-03-18 18:08:58.590268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2c778bb0b6'
down_revision = 'de323b0f5696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_expense', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('total_expense')

    # ### end Alembic commands ###
