"""add expense history

Revision ID: e9c87920b129
Revises: 35655bc0bfb1
Create Date: 2026-03-08 01:51:29.465363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c87920b129'
down_revision = '35655bc0bfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('paid_by', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_group_user'), type_='unique')
        batch_op.drop_constraint(batch_op.f('group_members_group_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('group_members_user_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('group_members_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('group_members_group_id_fkey'), 'groups', ['group_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_group_user'), ['group_id', 'user_id'], postgresql_nulls_not_distinct=False)

    op.drop_table('expense_history')
    # ### end Alembic commands ###
